name: oligocheck

channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.11
  - biopython
  # - bowtie2
  - click
  - colorama
  - expression
  - levenshtein
  - openpyxl
  - pandas
  - pip
  - polars
  - rich
  - seaborn
  - xlsx2csv
  - pip:
      - -e .
      - mygene
      - primer3-py
      - pyfastx
